README.md, package.json
Update readme and add start command
=> Update readme and add start command

.storybook/main.js, package-lock.json, package.json, src/components/social-share/social-share.js, src/components/social-share/social-share.scss, src/components/social-share/social-share.stories.js, src/index.js, src/styles.scss
Closes #11 
* Socials share component
* Knobs addon for storybook
=> feat: socials share

src/components/list-header/list-header.js, src/components/list-header/list-header.scss, src/components/list-header/list-header.stories.js, src/index.js
Created new ListHeader component
=> created ListHeader component

.storybook/preview-head.html, src/components/list-header/list-header.scss, src/components/social-share/social-share.scss, src/styles.scss
Add titilium global google font.
Change bulma variable for font sans serif.
Load google font for every storie.
=> Add titilium global google font

src/components/button/button.js, src/components/button/button.scss, src/components/button/button.stories.js, src/styles.scss
Closes #8
Implements the Button component
=> feat(button): Implemented the button component

.storybook/preview-head.html
Added the Titillium Web font back to the Storybook previews
=> chore: add Titillium Web font to Storybook preview

.github/workflows/publish.yml, package.json
- Added publish to npm action (On release)
- Adds org-scope in the package name
- Bump version
=> Add publish action

package.json
Closes 
Please mention the main changes this PR brings.
=> chore: change org name to code4ro and bump version

src/components/button/button.scss, src/components/header/header.js, src/components/hero/hero.scss, src/components/list-item/list-item.js, src/components/list-item/list-item.styles.scss, src/components/list/list.js, src/components/list/list.styles.scss
- Updated CSS classes for list/listItem components to avoid style collision
- Updated font size for button to fit the design
- Updated font wight for hero title to fit the design
- Removed horizontal padding for hero body to align with design
=> Styles: fix some css issues

src/components/list-item/list-item.js, src/components/list-item/list-item.stories.js
- Added `value` prop to the `listItem` component and return it `onClick` callback
- If the value is not defined, and we have `onClick`, it will return the default `event`
=> feat: add value prop to the listItem component

package-lock.json, package.json, rollup.config.js, src/components/footer/footer.js, src/components/footer/footer.stories.js, src/index.js
=> exported all components;

package.json, src/index.js
- Export `footer-links` components
=> chore: export footer-links

src/components/developed-by/developed-by.js, src/components/developed-by/developed-by.scss, src/components/incubated-by/incubated-by.js, src/components/incubated-by/incubated-by.scss
Used flexbox layout for DevelopedBy and IncubatedBy components
=> used flexbox layout for DevelopedBy and IncubatedBy components

src/components/footer/footer.js, src/components/footer/footer.scss, src/components/footer/footer.stories.js, src/components/header/header.js, src/components/header/header.scss, src/styles.scss
=> Add container from bulma and use display grid to header/footer.

src/components/search-input/search-input.js, src/components/search-input/search-input.scss, src/styles.scss
Changed SearchInput enhancement to use Bulma CSS and to show Icon
=> SearchInput enhancement to use Bulma CSS

src/components/developed-by/developed-by.scss, src/components/incubated-by/incubated-by.js, src/components/incubated-by/incubated-by.scss
Fixed some fixes :) 
Removed unnecessary whitespace for developedBy and .container class from incubatedBy
=> Small layout fixes

src/components/header/header.scss
closes https://github.com/code4romania/taskforce-fe-components/issues/60
=> removed left right header padding

package-lock.json, src/components/accordion/accordion.js, src/components/accordion/accordion.scss, src/components/accordion/accordion.stories.js, src/components/button/button.js, src/components/button/button.stories.js, src/components/list-item/list-item.js, src/components/list-item/list-item.stories.js, src/components/list-item/list-item.styles.scss, src/icons/arrow-down.svg, src/styles.scss
- Added initial accordion component
- Guard for `undefined` `onClick` callback on `ListItem` component
- Added `nonOption` state to the `listItem` component (#61) 
- Aligned items on the center for the `listItem` content
=> [Feature] Implement accordion component

src/components/developed-by/developed-by.js
Closes https://github.com/code4romania/ce-ma-fac/issues/92
=> added diacritics in texts

package-lock.json, package.json, src/index.js
- Exported `accordion` component
- Bumped version
=> chore: export accordion component

package-lock.json, package.json, src/components/header/header.scss
https://github.com/code4romania/ce-ma-fac/issues/101
=> Add hover state on header links and make font bigger.

README.md, src/components/banner/banner.js, src/components/banner/banner.scss, src/components/banner/banner.stories.js, src/index.js
tried adding a banner component ¯\_(ツ)_/¯
=> added banner component

.storybook/main.js, .storybook/preview.js, package-lock.json, package.json
Please mention the main changes this PR brings:
- Adds the ability to test on mobile device resolutions by using the viewport addon
It adds a tiny button to the top bar
Known issues:
- there is a console warning that appeared with the introduction of the addon (which is really weird). The functionality looks like is not affected though
=> Adding the viewport addon for mobile testing

src/components/developed-by/developed-by.js, src/components/developed-by/developed-by.scss, src/components/hero/hero.js, src/components/hero/hero.scss, src/components/incubated-by/incubated-by.scss, src/components/instruments-item/instruments-item.scss, src/components/instruments/instruments.js, src/components/instruments/instruments.scss, src/components/list/list.stories.js, src/components/list/list.styles.scss
- use flex instead of grid for list component
- improve mobile styles for developed-by component
- improve mobile styles for incubated-by component
- remove column class collision for the instruments component
- update hero component and fix responsive sizes
=> Update styles for different component & improve responsive styles

package.json, src/components/banner/banner.js, src/components/banner/banner.stories.js, src/components/subscribe/mailchimp-subscribe.js, src/components/subscribe/mailchimp-subscribe.stories.js
It adds the `compact` flag to `MailchimpSubscribe` component so it can control the layout of the underlying `SubscribeForm` component.
=> Propagate the compact flag through mailchimp wrapper

package-lock.json, package.json, src/components/banner/banner.scss, src/components/sidebar-menu-item/sidebar-menu-item.js, src/components/sidebar-menu-item/sidebar-menu-item.scss, src/components/sidebar-menu-item/sidebar-menu-item.stories.js, src/components/sidebar-menu/sidebar-menu.js, src/components/sidebar-menu/sidebar-menu.scss, src/components/sidebar-menu/sidebar-menu.stories.js
=> Create SidebarMenu and SidebarMenuItem components

src/components/sidebar-menu/sidebar-menu.scss
- Removed unnecessary padding for the sidebar menu
=> styles: remove unnecessary padding

src/components/incubated-by/incubated-by.js
closes https://github.com/code4romania/ce-ma-fac/issues/123
=> updated phrasing

src/components/checkbox/checkbox.stories.js
Changed the storybook example just so the checkbox component is usable with the said example.
- N/A this is a documentation only PR for the time being
=> Added value to the checkbox

package.json, src/components/banner/banner.scss
- Fixes css for the banner
- Closes #103
=> fix: missing semicolon for the banner css

.github/workflows/eslint.yml, .github/workflows/publish.yml, src/components/list-item/list-item.js, src/components/radio-list/radio-list.js, src/components/select/select.js, src/components/select/select.stories.js, src/index.js
- Adds ESLint GitHub Action
- Fixes existing ESLint errors
=> chore: add ESLint GitHub Action

src/components/social-share/social-share.js, src/components/social-share/social-share.scss
- Added a class to the social share label, nudged the label 4px up to visually center on icons
- Closes  #111
=> nudge the social share label to appear visually aligned to the icons

package-lock.json, package.json, src/components/search-result-list-item/search-result-list-item.js, src/components/search-result-list-item/search-result-list-item.stories.js, src/components/search-result-list-item/search-result-list-item.styles.scss, src/index.js
Add search list item component
=> Add search result list item

src/components/social-share/social-share.js
- Translated "share on" to Romanian ( "Distribuie pe" )
- Closes https://github.com/code4romania/taskforce-fe-components/issues/112
=> Translate social share buttons text

src/components/search-input/search-input.js, src/components/search-input/search-input.scss, src/components/search-input/search-input.stories.js
Added onClick prop for Search Input component
Added onEnter prop for Search Input component
- Closes #110
=> Add Search Input Events(#110)

src/components/input/input.js, src/components/input/input.stories.js, src/components/label/label.js, src/components/label/label.scss, src/components/label/label.stories.js
Added the option to mark a label as secondary. It has a smaller font size and a normal font weight.
The input element also has the option to have a secondary label besides the existing one. It could contain additional information.
=> Added secondary label

src/components/sidebar-menu-item/sidebar-menu-item.js, src/components/sidebar-menu-item/sidebar-menu-item.scss
- Fixes: The list item renders false and undefined on list item class
- Fixes https://github.com/code4romania/ce-ma-fac/issues/160
- Closes
=> Fixed menu item appears as selected on mobile devices

src/components/accordion/accordion.js, src/components/accordion/accordion.scss, src/components/accordion/accordion.stories.js, src/images/icons/arrow-down.svg
- the accordion component has been updated with the new design
- the accordion component accepts a logo
=> 108 update accordion component layout

src/components/developed-by/developed-by.js, src/components/developed-by/developed-by.scss, src/components/developed-by/developed-by.stories.js
Linked issue: #113 
- The partners logos are now customizable
- partners can be removed on demand
- second line caption and logos are customizable
- component usage is backwards compatible
=> DevelopedBy component with parameters

src/components/form/form.js, src/components/form/form.stories.js, src/components/form/form.test.js
With the previous way the Form was not showing in the exports of the package
- using named export to be in line with the rest of the components and enabling exporting of Form from the package
=> Fixing issue related to wrong way of exporting 

.eslintrc, package-lock.json, package.json
=> Add eslint rule for stateless function component.

package.json, src/components/form/decisionTree.js, src/components/form/form.js, src/components/form/form.test.js, src/components/form/multipleChoice.js, src/components/form/multipleChoice.scss, src/components/form/multipleChoice.test.js
- Multiple choice added to the types of question in the from - copied from CeMaFac
It should assume default behaviour in terms of next question.
Should close this: https://github.com/code4romania/taskforce-fe-components/issues/136
=> Added multiple choice type - copied from CeMaFac

.gitignore, package-lock.json, package.json, src/components/input/input.js, src/components/input/input.stories.js
Added the number input type
- Closes #135
=> feat(input): Added number input type

src/components/instruments-item/instruments-item.js, src/components/instruments-item/instruments-item.scss, src/components/instruments/instruments.stories.js
- Closes https://github.com/code4romania/taskforce-fe-components/issues/141
=> add orange and blue sidebar items colors

package-lock.json, package.json, src/components/form/form.js
=> Fix form propType

package.json, src/components/developed-by/developed-by.scss, src/components/developed-by/developed-by.stories.js
- Improve responsiveness for DevelopedBy logos
- Closes https://github.com/code4romania/ce-ma-fac/issues/179
=> Improve responsiveness for DevelopedBy logos

package.json, src/components/dropdown-search/dropdown-search.js, src/components/dropdown-search/dropdown-search.scss, src/components/dropdown-search/dropdown-search.stories.js, src/components/dropdown-search/dropdown.test.js, src/index.js
- Implemented a new component for Dropdown Search to be used for city and county as displayed in #147.
- This closes #147.
- Version was bumped to 1.0.11 and component exported at top level in `index.js`
=> Implemented DropdownSearch component for county and city. Closes #147.

src/components/dropdown-search/dropdown-search.js, src/components/dropdown-search/dropdown-search.stories.js, src/components/dropdown-search/dropdown.test.js
Closes https://github.com/code4romania/taskforce-fe-components/issues/152
=> Updating the displayed options when the props for options is changed

src/components/form/data/decisionTree.js, src/components/form/datePicker.js, src/components/form/form.js, src/components/form/form.test.js, src/components/form/inputQuestion.js, src/components/form/multipleChoice.js
Added datepicker type to the form
Renamed "FREE_TEXT" to "INPUT" to described the type of question
=> Form date picker

package.json, src/components/logo/logo.js, src/components/logo/logo.stories.js
- Add `target` prop to Logo component
- Closes https://github.com/code4romania/taskforce-fe-components/issues/154
=> Open url in same tab

src/components/input/input.js, src/components/input/input.stories.js
- Add extra props to `Input` component
- Props added `maxlength`, `minlength`, `title`, `pattern`
- Closes https://github.com/code4romania/taskforce-fe-components/issues/159
=> feature - Add input props used in phone validation

package.json, src/components/input/input.js, src/components/input/input.stories.js
- Added validationMessages prop to Input, in order to set custom validation messages
regarding https://github.com/code4romania/stam-acasa/issues/262
=> [stam-acasa] Add custom validation message

src/components/form/form.js, src/components/form/form.scss, src/components/form/staticText.js
- Changed buttons order
- Fixed margin issues for final node
- Fixed margin issues for mall resolution
- Closes [code4romania/stam-acasa/#316](https://github.com/code4romania/stam-acasa/issues/316)
=> feat: reversed buttons & fixed styling issues

src/a11y.js, src/components/list-item/list-item.js, src/components/list/list.js
- added role="list" on List
- added role="listitem" on ListItem
- added tabIndex on ListItem
- handle Enter/Space keypress on ListItem
=> feat: Make list-item accessible by keyboard. Closes #168

src/components/accordion/accordion.js, src/components/sidebar-menu-item/sidebar-menu-item.js, src/components/sidebar-menu/sidebar-menu.js
added SidebarMenu accesibility props
added Accordion tabindex and hide/show on enter
(Make sidebar-menu-item component accessible for keyboard navigation #169)
(Make accordion component accessible for keyboard navigation #170)
=> feat: SidebarMenu and Accordion components accesibility, 

package.json, src/components/accordion/accordion.js, src/components/list-item/list-item.js, src/components/sidebar-menu-item/sidebar-menu-item.js
- Fixes the way we use the `onEnterOrSpace` helper
=> fix: usage of onEnterOrSpace util

src/components/form/form.js
Closes https://github.com/code4romania/taskforce-fe-components/issues/183
=> more diacritics

package-lock.json, package.json, src/components/footer/footer.js, src/components/footer/footer.scss
Added an Easter egg for people who select text in footers:
=> Added easter egg in footer

src/components/temperature-chart/temperature-chart.js, src/components/temperature-chart/temperature-chart.stories.js
- Reverses axes for the `TemperatureChart` component
=> refactor: reverse temperature chart axes

package.json, src/components/temperature-chart/temperature-chart.js, src/components/temperature-chart/temperature-chart.stories.js
- Display the right order for the temperature chart component items
=> refactor: display the right order for the temperature chart items

package-lock.json, package.json, src/components/form/data/ceMaFac.js, src/components/list-item/list-item.js
- Add support for html inside list item
=> Add support for html inside list

package.json, src/components/form/data/decisionTree.js, src/components/form/form.js
- Implemented option to hide the back button on certain questions, like ,for example, the last question on the form
- Helps close https://github.com/code4romania/stam-acasa/issues/416
=> Added option to hide the back button

src/components/list-item/list-item.js, src/components/list/list.js
- Use proper tags for List and ListItem components
- Closes #182
=> [182] use proper tags in List and ListItem
